version: '3.6'
services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.4.1'
        volumes:
            - './elasticdata:/usr/share/elasticsearch/data'
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
    kibana:
        image: 'docker.elastic.co/kibana/kibana:7.4.1'
        ports:
            - '5601:5601'
        environment:
            - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'